changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Bugfixes
      labels:
        - bug
    - title: Improvements
      labels:
        - improvement
    - title: Other
      labels:
        - '*'
        exclude:
          - feature
          - bug
          - improvement