create table public.foods (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  source jsonb null,
  name text not null,
  macros json not null,
  ean text null,
  constraint foods_pkey primary key (id),
  constraint foods_ean_key unique (ean),
  constraint foods_source_key unique (source)
) TABLESPACE pg_default;

create index IF not exists idx_foods_name_gin on public.foods using gin (name gin_trgm_ops) TABLESPACE pg_default;