create table public.recent_foods (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint not null,
  last_used timestamp with time zone not null,
  times_used integer not null,
  type text not null default 'food'::text,
  reference_id bigint not null,
  constraint recent_foods_pkey primary key (id),
  constraint recent_foods_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;

create index IF not exists idx_recent_foods_user_last_used on public.recent_foods using btree (user_id, last_used desc) TABLESPACE pg_default;