create table public.recipes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  items jsonb not null default '[]'::jsonb,
  owner bigint not null,
  name text not null,
  prepared_multiplier real not null,
  constraint recipes_pkey primary key (id),
  constraint recipes_owner_fkey foreign KEY (owner) references users (id)
) TABLESPACE pg_default;

create index IF not exists idx_recipes_name_gin on public.recipes using gin (name gin_trgm_ops) TABLESPACE pg_default;
create index IF not exists idx_recipes_owner on public.recipes using btree (owner) TABLESPACE pg_default;